
server:
  port: 8080  #tomcat端口
#spring:
#  datasource:
#    url: jdbc:mysql://10.10.13.81:3306/jkinfo
#    username: jkinfo
#    password: Dyf_2019
#  mybatis:  #mybatyis的配置
#  mapper-locations: classpath:mapper/*.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
#########################使用durid连接池##################################
durid:
  datasource:
    url: jdbc:mysql://60.205.177.133:3306/weixin_project?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: Wwt_123456
    driverClassName: com.mysql.jdbc.Driver
    #初始化大小
    initialSize: 20
    #最小连接数
    minIdle: 20
    #最大连接数
    maxActive: 200
    #连接等待超时时间
    maxWait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    #校验sql、oracle配置，如果不配置validationQuery，则下面三项无效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

spring:
  thymeleaf:
    prefix: classpath:/templates/ # 页面默认前缀目录